### PR TITLE
Authenticate with Oauth (ombu_labs-auth) 

### PR DESCRIPTION
**Pull request by etagwerker**
This PR is an attempt to authenticate with GitHub instead of basic HTTP auth.

### CODE REVIEW

**Comment by kindoflew** [comment]
Hello @bronzdoc! could you review this when you have a chance? thanks!

**Comment by JuanVqz** [comment]
@etagwerker, could you please solve the conflicts? Thanks!

**Comment by etagwerker** [comment]
@JuanVqz @arielj I just fixed the conflicts here. Unfortunately I haven't been able to make it work while testing in development.

Any ideas?

**Comment by arielj** [comment]
> @JuanVqz @arielj I just fixed the conflicts here. Unfortunately I haven't been able to make it work while testing in development.
> 
> Any ideas?

I see it has things from the previous setup, maybe you can compare the diff with the one from the fastruby.io PR https://github.com/ombulabs/fastruby.io/pull/580, this one is working and it's done from scratch based on the latest code from main (that's not yet released on rubygems)

Maybe it's easier to start this integration from scratch based on https://github.com/ombulabs/fastruby.io/pull/580 ? it's not really that much code and I see this and the one from FastRuby PRs are quiet different

**Comment by FionaDL** [comment]
@etagwerker do you want to close this PR and have the recruitment team take this over. We can do what Ariel suggests of starting over using the fastruby PR as an example?

**Comment by etagwerker** [comment]
@FionaDL @arielj sounds good, thanks! 👍🏼

**Pull request closed without merging**
