### PR TITLE
COSA-1109 Added dropdown for campaign and content and sorted the drop…

### PR DESCRIPTION
**Pull request by ashwinisukale**
https://ombulabs.atlassian.net/browse/COSA-1109

Added dropdown for campaign and content
Sorted the values in the dropdown

### CODE REVIEW

**Review by FionaDL — APPROVED** [review]
@ashwinisukale this looks good to me, @gelsey to you want to QA this? EDIT: sorry, @ashwinisukale I merged Gelsey's PR an d now there are conflicts

**Comment by ashwinisukale** [comment]
@FionaDL I have resolved the conflicts

**Comment by ashwinisukale** [comment]
Also here some value are CamelCase Some are smallcase, are we going to keep them as it is? shall I make all of them in same case, or its intentional?

**Comment by FionaDL** [comment]
@ashwinisukale since we were told that it is fine as long as they are consistent I think we are good on this. @torresga do you want to QA?

**Review by torresga — APPROVED** [review]

**Pull request merged**
