### PR TITLE
COSA-1095: Clone shareable links

### LINKED ISSUE #7: [FEATURE] Add a way to clone shareable links
As a marketer sometimes I want to share a link more than once: Once on Twitter and then again on LinkedIn. 

The parameters for both shareable links are very similar. The main thing that changes is the source and the medium. 

## For Twitter 

Source: Twitter 
Medium: Tweet

## For LinkedIn 

Source: LinkedIn
Medium: Post 

All other details remain the same. 

It would be great if one could "clone" a shared link. It could be a "Clone" link right next to an item in the Shares section: 

Screen Shot 2022-11-18 at 9 40 07 AM

When I click the Clone link it should open up a /shares/new page and pre-populate the details with the cloned link: 

Screen Shot 2022-11-18 at 9 41 24 AM

This would save us a few seconds per new link.

### PR DESCRIPTION
**Pull request by torresga**
This PR resolves #7.

Jira ticket ID here:
https://ombulabs.atlassian.net/browse/COSA-1095

Screenshots of behavior:
Screen Shot 2023-04-28 at 9 23 50 AM

Screen Shot 2023-04-28 at 9 24 00 AM

### CODE REVIEW

**Review by etagwerker — CHANGES_REQUESTED** [review]
@torresga Looks good, could you please add a test for this new feature?

**Comment by etagwerker** [comment]
@torresga CI is failing because it's trying to connect to Chat GPT. Maybe you need to make it so that it doesn't try to consume their API from our dev and test environments?

**Comment by torresga** [comment]
@etagwerker Hey sorry Ernesto, I pushed up some changes that weren't working because @ashwinisukale offered to help me fix some issues I was having. I will push up my changes and tag you when I am ready for you to re-review!

**Review by etagwerker — APPROVED** [review]
👍

**Pull request merged**
